project:
  type: website
  output-dir: docs   # ensures GitHub Pages will work
  resources:
    - CNAME

website:
  title: "#day21"
  navbar:
    background: "#8064A2"  # This sets the banner to your logo purple  #8064A2 old colour #6A317F
    type: dark             # This makes the text "Home", "About", etc. white
    logo: images/day21_transparent.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: public.qmd
        text: Public
      - href: professionals.qmd
        text: Professionals
      - href: project-team.qmd
        text: Project team
      - href: endorsements.qmd
        text: Endorsements
      - href: petition.qmd
        text: Petition
      - href: references.qmd
        text: References
    right:
      - icon: instagram
        href: https://www.instagram.com/postnatalcontraception
        

format:
  html:
    pretty_urls: true
    include-in-header: meta.html
    theme: darkly
    bootstrap-icons: true
    css: styles.css
    toc: true

editor: visual
